#!/data/data/com.termux/files/usr/bin/bash

cd $HOME

termux-wake-lock
pkg install root-repo x11-repo qemu-utils qemu-system-aarch64 qemu-system-x86-64 -y
clear

# Download file
wget https://github.com/xiv3r/termux-windows-10/archive/refs/tags/win10.iso

# Set qemu configuration 
read -p "Allocate Size Of RAM ex: 2GB is = 2048 : " ram
echo "[*] VNC Server Is Running..."
echo -e "Your VNC Server IP is:\e[1;96m 127.0.0.1:1"
qemu-system-x86-64 -m $ram -cdrom win10.iso -vnc 127.0.0.1:1 & pid=$!
